import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Card from '../components/card';

const Home: NextPage = () => {
	return (
		<div className={'px-0 py-8'}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main
				className={
					'min-h-screen px-16 py-0 flex-1 flex-col justify-center items-center'
				}
			>
				<h1 className={'text-blue-500'}>
					Welcome to <a href='https://nextjs.org'>Next.js!</a>
				</h1>

				<p className={'text-center'}>
					Get started by editing{' '}
					<code className={'bg-slate-50 rounded-md p-3 text-lg font-mono'}>
						pages/index.tsx
					</code>
				</p>

				<div className={'grid grid-cols-1 mx-56'}>
					<Card
						href='https://nextjs.org/docs'
						title='Documentation &rarr;'
						content='Find in-depth information about Next.js features and API.'
					/>

					<Card
						href='https://nextjs.org/learn'
						title='Learn &rarr;'
						content='Learn about Next.js in an interactive course with quizzes!'
					/>

					<Card
						href='https://github.com/vercel/next.js/tree/canary/examples'
						title='Examples &rarr;'
						content='Discover and deploy boilerplate example Next.js projects.'
					/>

					<Card
						href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
						title='Deploy &rarr;'
						content='Instantly deploy your Next.js site to a public URL with Vercel.'
					/>
				</div>
			</main>

			<footer className='flex flex-1 px-0 py-8 border-t-2 border-slate-50 justify-center items-center'>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
					className='flex items-center justify-center flex-grow'
				>
					Powered by{' '}
					<span className='h-4 ml-2'>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;
